### ISSUE TITLE
Rate My Agent Logo is missing the link to the agent page.

### ISSUE THREAD

**Issue by mattneal-stafflink** [mattneal-stafflink/rate-my-agent-review#3]
As per the requirements from RMA, we need to set up a link to go to the agent's page on RMA.

**Comment by gian-stafflink** [comment]
Issue was missing a href fixed with pull https://github.com/mattneal-stafflink/rate-my-agent-review/commit/8ccdc77690df973d403bdfac48d61f0dbf998d44
